matrix:
  php:
    - "8.1"
    - "8.0"
    - "7.4"
    - "7.3"
    - "7.2"
    - "7.1"

clone:
  git:
    when:
      event:
        - tag
        - push
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  build:
    group: build
    image: 192.168.69.1:5000/php-ci:latest
    when:
      event:
        - tag
        - push
    secrets:
      - GITHUB_TOKEN
      - API_ID
      - API_HASH
      - BOT_TOKEN
      - DEST
    environment:
      - PHP_VERSION=${php}
      - TAG=${CI_COMMIT_TAG}
    commands:
      - tests/makephar.sh

services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_DATABASE=MadelineProto
      - MARIADB_USER=MadelineProto
      - MARIADB_PASSWORD=test
      - MARIADB_RANDOM_ROOT_PASSWORD=yes

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=MadelineProto
      - POSTGRES_USER=MadelineProto
      - POSTGRES_PASSWORD=test

  redis:
    image: redis